name: CI

on: [push]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: docker build -t go-static-web-docker .

      - name: Docker login
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Docker tag
        run: docker tag go-static-web-docker jackytck/go-static-web-docker:v0.0.1

      - name: Docker push
        run: docker push jackytck/go-static-web-docker:v0.0.1
